import type { AppState, Course } from '../types/state';
import type { AssessmentResult, Concept, DayKey } from '../types/domain';
import type { AiProvider } from '../lib/ai/contracts';
import { DAY_MS, dayKey, now } from '../domain/time';
import { effectiveMastery, hasAttempted } from '../domain/mastery';
import { isDue } from '../domain/srs';
import { intBetween, seededRng } from '../lib/rng';
import { buildCommit } from './commit';
import { reducer } from './reducer';
import { defaultProfile, defaultStreak } from './initial';
import { makeCourse } from './course';

/**
 * Demo history, GENERATED BY THE ENGINES rather than written down.
 *
 * Every day below is replayed through the real buildCommit() and the real
 * reducer, with nothing but the clock changed. So the streak, the XP totals,
 * the SM-2 intervals, the decayed mastery and the achievements are not
 * plausible-looking numbers typed into a fixture -- they are what this app
 * actually produces from those sessions, and they cannot drift away from the
 * engines because they have no independent existence.
 *
 * That distinction is the entire point. The build this replaces shipped
 * `streak: 6` and `sessions: 9` as literals inside a useMemo.
 */

/** Scaffolding for the demo tool, not product content: the shape of a
 *  fortnight's attendance. Two gaps, the first covered by a freeze. */
const ATTENDANCE: number[] = [13, 12, 11, 10, 9, 8, 7, /* 6 missed */ 5, 4, 3, 2, 1];

/** Only used when there is no course to hang history on. */
export const DEMO_TOPIC = 'The Roman Republic';

interface DemoSession {
  daysAgo: number;
  conceptId: string;
  score: number;
  durationMs: number;
}

/**
 * Misconception text derived from the concept's own name.
 *
 * Not subject-matter content: the concept names came from the model, and these
 * are structural statements about a learner's relationship to them. Writing
 * real misconceptions here would be exactly the hardcoding this whole phase
 * exists to avoid.
 */
function misconceptionFor(concept: Concept, variant: number): string {
  // Quote the concept name verbatim rather than lowercasing it. Concept names
  // come from a model and routinely contain proper nouns -- "Orientation: the
  // shape of Roman History" lowercased reads as a typo, not a sentence.
  const name = `“${concept.name}”`;
  const forms = [
    `Treated ${name} as a rule to memorise rather than something to apply.`,
    `Confused ${name} with the idea introduced just before it.`,
    `Got the definition right but could not use it on an unfamiliar example.`,
  ];
  return forms[variant % forms.length]!;
}

function assessmentFor(concept: Concept, score: number, rng: () => number): AssessmentResult {
  const misconceptions =
    score < 70 ? [misconceptionFor(concept, Math.floor(rng() * 3))] : [];
  return {
    score,
    correct: score >= 70,
    misconceptions,
    feedback: '',
    needsReview: score < 70,
  };
}

/**
 * Pick what would have been studied on a given day.
 *
 * Mirrors selectNextAction's priority rather than inventing one, so the history
 * looks like something this app would actually have produced: clear the queue
 * once it backs up, otherwise move forward, and only grind on old material when
 * there is nothing new.
 *
 * The first version of this preferred *any* due concept over new ones, which
 * quietly starved progression -- a freshly-studied concept is due again within a
 * day or two, so the simulated learner re-drilled concept two for a fortnight
 * and never unlocked concept three. Requiring the queue to actually back up
 * before reviewing is what makes the path advance.
 */
function chooseConcept(concepts: Concept[], today: DayKey, at: number): Concept | null {
  const open = concepts.filter((c) => c.status !== 'locked');
  if (open.length === 0) return null;

  const weakest = (list: Concept[]) =>
    list.reduce((a, b) => (effectiveMastery(a, at) <= effectiveMastery(b, at) ? a : b));

  const due = open.filter((c) => hasAttempted(c) && isDue(c, today));
  if (due.length >= 2) return weakest(due);

  const fresh = open.filter((c) => !hasAttempted(c));
  if (fresh.length > 0) return fresh.reduce((a, b) => (a.order <= b.order ? a : b));

  if (due.length > 0) return weakest(due);
  return weakest(open);
}

export interface DemoResult {
  state: Partial<AppState>;
  /** What actually came out, for an honest confirmation message. */
  summary: { sessions: number; streak: number; longest: number; totalXp: number; due: number };
}

/**
 * Build the demo state on top of `base`.
 *
 * Returns a partial AppState for LOAD_DEMO rather than mutating anything, so
 * the caller decides whether to commit it.
 */
export function buildDemoState(base: AppState, course: Course): DemoResult {
  const rng = seededRng('learnable-demo', course.topic);
  const at0 = now();

  // Start from a clean slate that keeps settings and the course. Replaying
  // sessions onto existing progress would double-count everything.
  let state: AppState = {
    ...base,
    onboarded: true,
    profile: { ...defaultProfile(at0 - 14 * DAY_MS), displayName: base.profile.displayName },
    courses: [{ ...course, concepts: course.concepts.map(freshConcept) }],
    activeCourseId: course.id,
    sessions: [],
    days: {},
    streak: defaultStreak(),
    achievements: {},
    lessonCache: {},
  };

  const planned: DemoSession[] = [];

  for (const daysAgo of ATTENDANCE) {
    const at = at0 - daysAgo * DAY_MS;
    const today = dayKey(at, state.settings.timeZone);
    const concepts = state.courses[0]!.concepts;

    // Two sessions a day: the default 30 XP goal is deliberately tuned so one
    // session does not clear it, so a one-session day would earn no streak.
    for (let i = 0; i < 2; i++) {
      const atSession = at + i * 20 * 60_000;
      const concept = chooseConcept(concepts, today, atSession);
      if (!concept) break;

      // Weighted toward decent-but-imperfect, with a real failure early on so
      // the misconception log, a lapse and the honest_learner arc all exist.
      const roll = rng();
      const score =
        daysAgo === 13 && i === 1 ? 40 : roll < 0.15 ? intBetween(rng, 35, 55) : roll < 0.55 ? intBetween(rng, 62, 78) : intBetween(rng, 82, 100);
      const durationMs = intBetween(rng, 150, 420) * 1000;

      const action = buildCommit(
        state,
        {
          courseId: course.id,
          conceptIds: [concept.id],
          mode: hasAttempted(concept) ? 'review' : 'lesson',
          startedAt: atSession - durationMs,
          assessment: assessmentFor(concept, score, rng),
          answers: {},
          correct: Math.round((score / 100) * 3),
          total: 3,
          hintsUsed: rng() < 0.2 ? 1 : 0,
        },
        atSession,
      );
      state = reducer(state, action);
      planned.push({ daysAgo, conceptId: concept.id, score, durationMs });
    }
  }

  // Statuses were last derived at the final simulated session; bring them to
  // the present so the path reflects however much has decayed since.
  state = reducer(state, { type: 'RESTATUS', payload: { at: at0, today: dayKey(at0, state.settings.timeZone) } });

  const today = dayKey(at0, state.settings.timeZone);
  const due = state.courses[0]!.concepts.filter((c) => hasAttempted(c) && isDue(c, today)).length;

  return {
    state: {
      onboarded: true,
      profile: state.profile,
      courses: state.courses,
      activeCourseId: state.activeCourseId,
      sessions: state.sessions,
      days: state.days,
      streak: state.streak,
      // Marked seen: these were awarded to a simulated fortnight, not earned in
      // front of anyone. Left unseen, the next results screen would announce a
      // pile of unlocks the user had no part in.
      achievements: Object.fromEntries(
        Object.entries(state.achievements).map(([id, a]) => [id, { ...a, seen: true }]),
      ),
      lessonCache: {},
    },
    summary: {
      sessions: planned.length,
      streak: state.streak.current,
      longest: state.streak.longest,
      totalXp: state.profile.totalXp,
      due,
    },
  };
}

function freshConcept(c: Concept, i: number): Concept {
  return {
    ...c,
    mastery: 0,
    peakMastery: 0,
    attempts: 0,
    lastStudiedAt: null,
    bestScore: 0,
    scoreHistory: [],
    misconceptions: [],
    markedKnown: false,
    masteryHistory: [],
    status: i === 0 ? 'current' : 'locked',
    review: { dueOn: null, intervalDays: 0, ease: 2.5, reps: 0, lapses: 0, snoozes: 0 },
  };
}

/**
 * Demo data with a course to hang it on, generating one first if needed.
 *
 * Goes through the same provider as the rest of the app, so `Load demo data`
 * with VITE_API_MODE=live genuinely asks the backend for a path.
 */
export async function seedDemo(ai: AiProvider, state: AppState): Promise<DemoResult> {
  const existing = state.courses.find((c) => c.id === state.activeCourseId) ?? state.courses[0];
  if (existing) return buildDemoState(state, existing);

  const concepts = await ai.generatePath({
    topic: DEMO_TOPIC,
    level: state.settings.level,
    dailyTimeMin: state.settings.dailyTimeMin,
    goal: '',
    // A fixture length for the seeded demo, not a limit: paths are any length
    // now (settings.pathLength, and /path/extend for going further). Pinned
    // here only so the demo stays reproducible between runs.
    conceptCount: 7,
  });
  const at = now();
  return buildDemoState(
    state,
    makeCourse({
      id: `c_${at}`,
      topic: DEMO_TOPIC,
      goal: '',
      level: state.settings.level,
      dailyTimeMin: state.settings.dailyTimeMin,
      createdAt: at,
      concepts,
    }),
  );
}
