import { Link } from 'wouter';
import { CaretDown, Lightning } from '@phosphor-icons/react';
import { Ring } from '../components/Ring/Ring';
import { StreakFlame } from '../components/StreakFlame/StreakFlame';
import { ROUTES } from '../router/routes';
import { isLive } from '../lib/ai';
import s from './TopBar.module.css';

export interface TopBarStats {
  courseName: string;
  streak: number;
  xpToday: number;
  dailyGoalXp: number;
  totalXp: number;
  level: number;
  initials: string;
}

export interface TopBarProps {
  stats: TopBarStats;
}

/**
 * Every control here navigates somewhere.
 *
 * The build this replaces had six sidebar buttons with no onClick and a "tag"
 * that looked like a control but was a div. The rule going forward: nothing in
 * the chrome looks interactive unless it is.
 */
export function TopBar({ stats }: TopBarProps) {
  const { courseName, streak, xpToday, dailyGoalXp, totalXp, level, initials } = stats;
  const goalPct = dailyGoalXp > 0 ? xpToday / dailyGoalXp : 0;

  return (
    <header className={s.bar}>
      <Link href={ROUTES.path} className={s.course}>
        <span className={s.courseName}>{courseName}</span>
        <CaretDown size={14} weight="bold" />
      </Link>

      {/*
        SAYS WHICH PROVIDER WROTE WHAT YOU ARE READING.

        `isLive` has existed, typed and exported, since the provider seam was
        built -- and nothing read it. So with no backend the app served
        simulated lessons and a simulated curriculum with no indication
        whatsoever that a model had not written them. That is the quiet kind of
        dishonesty this project exists to remove: not a fabricated number, but
        real-looking content presented as something it is not.

        It cost real confusion. A simulated Spanish path opening on "Core
        building blocks" reads as a bad prompt, so the search for the fault went
        to the prompts -- which were fine, and were never involved.

        Rendered only in mock mode. A permanent "LIVE" badge would be noise on
        the normal path; the badge is for the state that needs explaining.
      */}
      {!isLive && (
        <span
          className={s.simulated}
          title="No model is connected. Lessons and paths are generated by the built-in simulator in lib/ai/mockProvider.ts, which knows the shape of a course but not your subject. Run with VITE_API_MODE=live against the backend for real content."
        >
          Simulated
        </span>
      )}

      <div className={s.spacer} />

      <div className={s.stats}>
        <Link
          href={ROUTES.schedule}
          className={`${s.stat} ${s.statStreak}`}
          title={streak > 0 ? `${streak}-day streak` : 'No active streak'}
        >
          <StreakFlame size={22} cold={streak === 0} />
          {streak}
        </Link>

        <Link href={ROUTES.today} className={s.stat} title={`${xpToday} of ${dailyGoalXp} XP today`}>
          <Ring value={goalPct} size={26} thickness={4} tone="go" />
        </Link>

        {/* .xpLabel is hidden under 900px, so on a phone this link had no
            accessible name at all. The two links either side survived only
            because they already carried `title`. */}
        <Link
          href={ROUTES.progress}
          className={`${s.stat} ${s.statXp}`}
          aria-label={`${totalXp.toLocaleString()} XP, level ${level} — see your progress`}
          title={`${totalXp.toLocaleString()} XP · Level ${level}`}
        >
          <Lightning size={18} weight="fill" />
          <span className={s.xpLabel}>{totalXp.toLocaleString()}</span>
          <span className={s.level}>Lv {level}</span>
        </Link>

        <Link href={ROUTES.profile} className={s.avatar} aria-label="Profile">
          {initials}
        </Link>
      </div>
    </header>
  );
}
